print("Nama Saya :Achmad Rifa'i Ramadhan")
print("NIM : ")
print("Kelas : TI04")
print("Alamat :")
print(" ")
print("Nama Teman Saya : Swatu Sholat Asky")
print("NIM : 0110223135")
print("Kelas : TI04")
print("Perum Bumi Sakina Lestari Blok B1 No 1")
print(" ")
print(14+6)
print(" ")
print(39-19)
print(" ")
print(5*4)
print(" ")
print(100/5)